server {
    listen 80;
    server_name _;

    root /var/www/mytradingsystem;
    index index.html;

    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
    add_header Pragma "no-cache" always;
    add_header Expires "0" always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /last_update.txt {
        add_header Cache-Control "no-cache, no-store, must-revalidate" always;
    }
}
